### ISSUE TITLE
UE4 support

### ISSUE THREAD

**Issue by Realitian** [brkho/real-time-pbr#2]
Hi Brian
Awesome code as I think!
Btw, could you explain shortly about word of UE4 in sentence of "Physically based material system and lighting (based on UE4)"?
What do you mean Unreal Engine 4 based?
material was exported from UE4? or shaders were made by UE4 style?
Cheers.

**Comment by brkho** [comment]
Shaders were made in UE4 style. See [this paper](http://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf) for more details.
